# Generated by Django 5.1.1 on 2024-10-07 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('full_name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngineerDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers.engineer')),
            ],
        ),
        migrations.AddField(
            model_name='engineer',
            name='departments',
            field=models.ManyToManyField(through='engineers.EngineerDepartment', to='departments.department'),
        ),
    ]
